pipeline {
    agent any 

    tools {
        maven 'Localmaven'
    }

    stages {
        stage ('Build-Maven') {
            steps {
                sh '''
                    cd ./maven/simple-war/
                    mvn clean package
                    cd ./target/
                    ls
                '''
            }
        }

        stage ('Deploy-Tomcat') {
            steps {
                script {
                    deploy adapters: [tomcat10(credentialsId: 'tomcat', path: '', url: 'http://54.84.102.17:9090//')], 
                                     contextPath: '/itdefined-war-1.0.0', 
                                     war: 'maven/simple-war/target/itdefined-war-1.0.0.war'
                }
            }
        }
    }

}
